### ISSUE TITLE
Create `api_compliance_report` function (or similar)

### ISSUE THREAD

**Issue by valentineap** [inlab-geo/espresso#105]
It would be useful to be able to easily generate a report that can be run on an instance of EspressoProblem (`p`) that reports on:

1. All API-required functions and attributes, and whether they are currently implemented for `p`
2. All API-optional functions and attributes, and whether they are currently implemented for `p`
3. Any additional functions/attributes that that `p` is exposing

This will allow a contributor to easily check where things stand with their submission. It will also allow us to easily monitor the non-required aspects of `p`. In particular, if we decide to add any new `optional` feature to the API, it will be useful to be able to easily identify examples that do *not* currently implement that feature, but which perhaps should. E.g. `SimpleRegression` does not currently have plotting functions etc, probably because we only thought of that after we'd implemented the original version.

I envisage something that prints a report something like:
```
Required attributes: 5/7 implemented
.forward()   - OK
.good_model - ***Not implemented***
.starting_model - OK
[....]


Optional attributes: 3/14 implemented
.plot_data() - OK
.plot_model() -***Not implemented***

Additional attributes: 3 implemented
.foo()
.bar()
.foobar

<classname> is not API-compliant.
```
and perhaps returns some summary stats i.e. True/False for compliance, percentage of required fields implemented, percentage of optional fields implemented, number of additional functions.

Ideally the definitions of what is required and optional could be dynamically generated by parsing the base class, so that we don't need to worry about updating the compliance report function if the API changes.

This function could perhaps be divided into two -- one that does the checking and generates underlying data, and a separate one that deals with pretty-printing the results. It would probably then be appropriate to update our validation script to make use of this new function.

**Comment by valentineap** [comment]
Perhaps connected to this -- it would be nice to have the ability to generate a list of all examples that implement a specific set of options, e.g. "I need examples that define a prior model distrbution and have the ability to compute a jacobian -- what can Espresso offer here?"

**Comment by jwhhh** [comment]
With #112 the Espresso machine is [restructured into pipelines](https://drive.google.com/file/d/1wT7NiMOSPqniGAshEGlVz9O9Qfi1qGej/view?usp=sharing) and the following functions are added:
- `raw_compliance_report()`
- `compliance_report()`
- `pprint_compliance_report()`

With #118 the comment above is resolved by extending `list_problems()` and `list_problem_names()` functions. (e.g. `espresso.list_problems(["jacobian", "plot_model"])`)
