### ISSUE TITLE
Consolidate all build/deploy functions into `espresso_machine`

### ISSUE THREAD

**Issue by valentineap** [inlab-geo/espresso#110]
See #107

**Comment by jwhhh** [comment]
Following a discussion between Andrew and myself, we decided that we could leave our current files and folders as they are, but move our self-defined documentation extensions also to the `tools` folder so that they are easy to track.

We did consider renaming `tools` into `espresso_machine` though.

**Comment by jwhhh** [comment]
Now with #116 we've moved `src/espresso/_machine/` into `espresso_machine/doc_utils/`, and `tools/` into `espresso_machine/`.
