### ISSUE TITLE
Rename package from `cofi_espresso` to `geo_espresso`

### ISSUE THREAD

**Issue by jwhhh** [inlab-geo/espresso#111]
We can have the package name (on PyPI) to be different from the module name (used for import).

For example, scikit-learn is the name when we install it, and sklearn is the name to import.

So Andrew and I decided that we can have a pypi package called something like `espresso-geo` and then `import espresso`.

- [x] Edit `pyproject.toml`, etc.
- [x] Change subfolder name so that it's `import espresso` instead of `import cofi_espresso`
- [x] Make sure all existing examples work

**Comment by valentineap** [comment]
[ ] Move docs to espresso-geo.readthedocs.io
[ ] Update all docs, readmes etc to reflect new names

**Comment by jwhhh** [comment]
Naming change is completed by #116. I'll close this issue after `cofi-examples` is updated accordingly.
