### ISSUE TITLE
Any plan add surface wave dispersion curve forward function?

### ISSUE THREAD

**Issue by xichaoqiang** [inlab-geo/espresso#141]
@jwhhh Thanks for sharing this great package.

This package and cofi is powfull to do reseach.

And is there any plane to add surface wave dispersion curve forward and inversion function to esspresso and cofi?

Best ragards,
Xi

**Comment by jwhhh** [comment]
Hi Xi,

We have had a surface wave inversion example in Espresso now: https://geo-espresso.readthedocs.io/en/latest/user_guide/contrib/generated/_surface_wave_tomography/index.html

At the same time, here's a CoFI example that uses the above: https://cofi.readthedocs.io/en/latest/examples/generated/field_data/sw_tomography.html

Cheers,
Jiawen
