### ISSUE TITLE
ModuleNotFoundError when using ReceiverFunctionInversionKnt

### ISSUE THREAD

**Issue by auggiemarignier** [inlab-geo/espresso#193]
https://github.com/inlab-geo/cofi-examples/issues/41

**Comment by auggiemarignier** [comment]
During the wheel building process, the `build` directory for the examples that have compiled aspects gets moved into its own python package for some reason.

e.g.

Following the `esspresso` build system, we have a package structure like

```
_esp_build
└── src
    └── espresso
        ├── CMakeLists.txt
        ├── __init__.py
        ├── _espresso_problem.py
        ├── _fmm_tomography
        │   ├── __init__.py
        │   ├── _fmm_tomography.py      <- CONTAINS A RELATIVE IMPORT OF fm2dss
        │   ├── build      <-  NOTICE THE BUILD DIRECTORY IS IN THE _fmm_tomography PACKAGE
        │   │   ├── CMakeCache.txt
        │   │   ├── cmake_install.cmake
        │   │   └── fm2dss.o       <- HERE'S THE BINARY WHICH CAN BE IMPORTED
        │   ├── datasets
        │   │   ├── ...
        │   ├── fmst
        │   │   ├── compile
        │   │   └── src
        │   │       └── fm2dss.f90       <- HERE'S THE ORIGINAL SOURCE CODE
        │   └── waveTracker.py
```


But when the wheels get unpacked we end up with


```
lib/python3.11/site-packages
└──_fmm_tomography      <- NEW SEPARATE PACKAGE NOT DISCOVERABLE WITH RELATIVE IMPORTS
| └── build
|    ├── fm2dss.o       <- HERE'S THE BINARY WHICH CAN NO LONGER BE IMPORTED
|    ├── globalp.mod
|    └── traveltime.mod
└──espresso
|    ├── __init__.py
|    ├── _espresso_problem.py
|    ├── _fmm_tomography
|    │   ├── __init__.py
|    │   ├── _fmm_tomography.py      <- CONTAINS A RELATIVE IMPORT OF fm2dss
|    │   ├── ...
|    │   ├── fmst
|    │   │   ├── compile
|    │   │   └── src
|    │   │       └── fm2dss.f90      <- HERE'S THE ORIGINAL SOURCE CODE
|    │   └── waveTracker.py



```

**Comment by auggiemarignier** [comment]
In the case of the `FmmTomography`, `fm2dss.o` is an executable.  For the two `ReceiverFunctionInversion` classes, the binaries are imported as `from .build import *`.

The latter can be fixed with a `try...except` block e.g.

```
        try:
            from .build import rf
        except ImportError:
            try:
                from __receiver_function_inversion_knt.build import rf
            except ImportError:
                raise ImportError(
                    "The forward code is not built. Please run the build script in the "
                    "problem folder."
                )
```

For the former, I wonder if there's a way to get `f2dss` installed in the `bin` directory

**Comment by auggiemarignier** [comment]
When the build runs on the CI the built contributions don't have a local `build` directory like I do when I build locally ([see logs here](https://github.com/inlab-geo/espresso/actions/runs/12078851762)).

**Comment by auggiemarignier** [comment]
After #197 this should be solved for systems where it's built from wheels.  sdist still a problem

**Comment by JuergHauser** [comment]
Zipfile with receiver function code re-wrapped/organised by @fmagrini with a `CMakeList.stxt` replacing `setup.py`. Could be placed into a seperate repository and thus used like `pyrf96`. Orignal C souce code is available here https://www.eas.slu.edu/People/LZhu/home.html

[pyrf_knt.zip](https://github.com/user-attachments/files/18069680/pyrf_knt.zip)

**Comment by auggiemarignier** [comment]
That's an option to get things working, but as I've just discovered (https://github.com/inlab-geo/pyrf96/issues/5) we will need to have everything on PyPI

**Comment by JuergHauser** [comment]
Still needs to be deployed on PyPI but  ReceverFunctionInversionKnt is now available here  https://github.com/inlab-geo/pyhk

**Comment by auggiemarignier** [comment]
Should be all sorted now after #195 , #202 for the receiver function examples.  I still expect problems for the `FmmTomography` but we'll sort that later.
