### ISSUE TITLE
Build script relies on assumptions about working directory

### ISSUE THREAD

**Issue by valentineap** [inlab-geo/espresso#32]
When attempting to run utils/build_package/build.py **from inside the utils directory** I get the following error:

> Traceback (most recent call last):
>   File "/Users/stdq61/projects/espresso/utils/build_package/build.py", line 95, in <module>
>     main()
>   File "/Users/stdq61/projects/espresso/utils/build_package/build.py", line 77, in main
>     move_pkg_source()
>   File "/Users/stdq61/projects/espresso/utils/build_package/build.py", line 41, in move_pkg_source
>     move_folder_content(PKG_SRC, BUILD_FOLDER)
>   File "/Users/stdq61/projects/espresso/utils/build_package/build.py", line 32, in move_folder_content
>     copytree(
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 566, in copytree
>     with os.scandir(src) as itr:
> FileNotFoundError: [Errno 2] No such file or directory: 'utils/build_package/_package_src'

Running from project root rather than utils/ works fine. I guess we should probably not rely on relative paths.

I am assigning this to @jwhhh rather than attempting to fix myself as I don't want to break things elsewhere.

**Comment by valentineap** [comment]
NB We should check other build scripts for similar issues.

**Comment by valentineap** [comment]
@valentineap is being annoying and running scripts from silly places:
```

stdq61@DA-C02GK3PJQ6W1 contrib % python ../utils/new_contribution/create_new_contrib.py polynomial_curve
🥰 Thanks for contributing!
We are generating new contribution component from template...

Traceback (most recent call last):
  File "/Users/stdq61/projects/espresso/contrib/../utils/new_contribution/create_new_contrib.py", line 90, in <module>
    main()
  File "/Users/stdq61/projects/espresso/contrib/../utils/new_contribution/create_new_contrib.py", line 57, in main
    template_files=getListOfFiles(TEMPLATE_FOLDER)
  File "/Users/stdq61/projects/espresso/contrib/../utils/new_contribution/create_new_contrib.py", line 16, in getListOfFiles
    listOfFile = os.listdir(dirName)
FileNotFoundError: [Errno 2] No such file or directory: 'utils/new_contribution/_template'
```

**Comment by jwhhh** [comment]
This is indeed a bug. Thanks Andrew for finding it. I fixed all the build and validation scripts but forgot to handle this one.
