### ISSUE TITLE
More flexible handling of problem metadata

### ISSUE THREAD

**Issue by valentineap** [inlab-geo/espresso#58]
At present we have embedded all the problem metadata into class variables:
```python
class MyShinyProblem(EspressoProblem):
    problem_title = "Shiny"
    author_names  = ["Andrew"]
    ...
```

I wonder if we should change to have a class variable, `metadata`, which holds a dictionary containing the metadata:
```python
class MyShinyProblem(EspressoProblem):
    metadata = {'problem_title':"Shiny", 'author_names':["Andrew"], ...}
```

The motivation would be two-fold: first, it makes it much easier to write functions that parse metadata, since they just need to operate on dictionaries; second, it becomes easier for us (or users) to define new metadata fields in future. We can still enforce required fields, e.g. 
```python
if not 'problem_title' in shiny.metadata.keys(): raise StupidUserError
```
but metadata-using-functions don't necessarily need to know about all metadata fields by name.

Thoughts?

**Comment by valentineap** [comment]
We could consider making this a [`defaultdict`](https://docs.python.org/3/library/collections.html#defaultdict-objects) to make it easy to assign default values to 'optional' fields...

**Comment by jwhhh** [comment]
Yeah, I like the idea of `defaultdict`. (And the exception name above 🤣)

This separates metadata from other problem-related fields 👍
