### ISSUE TITLE
Improve FMM example by returning model_shape

### ISSUE THREAD

**Issue by jwhhh** [inlab-geo/espresso#79]
More information is needed in the actual inversion - model_shape.

**Comment by valentineap** [comment]
I thought we were insisting that models are 1D arrays, and that any reshaping was the responsibility of the contributor? Each example should be for a fixed shape.



> On 27 Sep 2022, at 03:55, Jiawen ***@***.***> wrote:
> 
> [EXTERNAL EMAIL]
> 
> More information is needed in the actual inversion - model_shape.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

-- 
Dr Andrew Valentine
Assistant Professor, Department of Earth Sciences, Durham University
Hon. Senior Lecturer, Research School of Earth Sciences, The Australian National University

**Comment by jwhhh** [comment]
Yes, we still insist that the models are 1D. I just wanted to add `model_shape` as an _additional_ attribute for extra information. I realised this is needed when you want to calculate a smoothing regularisation matrix in 2D space.

**Comment by valentineap** [comment]
I think I’m missing something. If models are restricted to be 1D, and you know `model_size()` what information do you need that you don’t have?

> On 27 Sep 2022, at 07:47, Jiawen ***@***.***> wrote:
> 
> [EXTERNAL EMAIL]
> 
> Yes, we still insist that the models are 1D. I just wanted to add model_shape as an additional attribute for extra information. I realised this is needed when you want to calculate a smoothing regularisation matrix in 2D space.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.
> 

-- 
Dr Andrew Valentine
Assistant Professor, Department of Earth Sciences, Durham University
Hon. Senior Lecturer, Research School of Earth Sciences, The Australian National University

**Comment by jwhhh** [comment]
Maybe I should improve the wording. Instead of `model_shape`, maybe `ngrid_x` and `ngrid_y` make more sense?

`model_size` is still there by default, but we don't know the length and width of the rectangle with `model_size`. See [this figure](https://github.com/inlab-geo/cofi-examples/blob/main/notebooks/fmm_tomography/figs/fmm_true_model.png) as an example - it's a rectangle but not a square, so the shape cannot be inferred from `model_size`.

If I'd like to use a smoothing regularization term, then I need the spatial relationship between the grids, so I need to know the `shape` of the model, not only the `size`. 

I've [modified the code](https://github.com/inlab-geo/espresso/pull/86/files) so that it's clearer that `model_shape` is a problem-specific parameter now.
